# Generated by Django 6.0.7 on 2026-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWNER', '0002_categoryone_categorytwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rack_no', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
