# Generated by Django 6.0.7 on 2026-07-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWNER', '0003_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image_1', models.CharField(max_length=255)),
                ('image_2', models.CharField(blank=True, max_length=255, null=True)),
                ('image_3', models.CharField(blank=True, max_length=255, null=True)),
                ('category_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OWNER.categoryone')),
                ('category_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OWNER.categorytwo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OWNER.section')),
            ],
        ),
    ]
