# Generated by Django 6.0.7 on 2026-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWNER', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytwo',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
