# Generated by Django 6.0.7 on 2026-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWNER', '0007_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_available',
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
