# Generated by Django 6.0.7 on 2026-07-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OWNER', '0009_categoryone_gender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryone',
            name='gender_type',
        ),
    ]
