# Generated by Django 6.0.7 on 2026-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWNER', '0010_remove_categoryone_gender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryone',
            name='gender_type',
            field=models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom')], default='bride', max_length=10),
        ),
    ]
