# Generated by Django 6.0.7 on 2026-08-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OWNER', '0012_categorytwo_gender_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount (%)'), ('fixed', 'Fixed Discount (₹)'), ('category', 'Category Special'), ('occasion', 'Occasion Special')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
