# Generated by Django 6.0.7 on 2026-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_booking_cart_feedback_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
