# Generated by Django 6.0.7 on 2026-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_booking_payment_method_booking_rental_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
